# Generated by Django 3.2 on 2021-04-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userincome',
            name='source',
            field=models.CharField(max_length=266),
        ),
    ]
